# Generated by Django 3.2.13 on 2022-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1994-06-30'),
            preserve_default=False,
        ),
    ]
